### ISSUE TITLE
Tests pass incorrectly

### ISSUE THREAD

**Issue by exodist** [gphat/graphics-color#1]
https://metacpan.org/source/GPHAT/Graphics-Color-0.29/t/01-rgb.t

line 37. cmp_ok takes $want, $op, $got, $name. Many other tests in this file are correct, but this one is wrong.

Since `$op` starts with a `#` it is interpreted as a comment, as such the tests pas because $got is true.

This test only passes because of a Test::More bug, listed here: https://github.com/Test-More/test-more/issues/478

A new version of Test::More will be released shortly correcting the bug, at which point your tests will start to fail everywhere. You need to correct the tests that are missing an operator.

**Comment by gphat** [comment]
Fixed up and released. Thanks!

**Comment by eserte** [comment]
Unfortunately 0.30 still fails with recent Test::More versions. See http://analysis.cpantesters.org/solved?distv=Graphics-Color-0.30#mod%3ATest%3A%3AMore

**Comment by DannyThomas** [comment]
perl 5.20.1, Graphics-Color-0.30, Test-Simple-1.001009

```
t/01-rgb.t ............... 1/44 Number found where operator expected at (eval in cmp_ok) t/01-rgb.t line 38, near "$got #ff667f $expect);
```

fixed by adding missing 'eq'

```
root@noble$ diff -u Graphics-Color-0.30.orig/t/01-rgb.t Graphics-Color-0.30/t/01-rgb.t
--- Graphics-Color-0.30.orig/t/01-rgb.t 2014-11-21 09:43:46.000000000 +1000
+++ Graphics-Color-0.30/t/01-rgb.t  2014-11-26 17:12:30.722523942 +1000
@@ -34,7 +34,7 @@
 cmp_ok($color->as_integer_string, 'eq', '255, 102, 127, 0.00', 'integer string');
 cmp_ok($color->as_hex_string, 'eq', 'ff667f', 'hex string');
 cmp_ok($color->as_hex_string('#'), 'eq', '#ff667f', 'hex string with prepend');
-cmp_ok($color->as_css_hex, '#ff667f', 'hex string with prepend');
+cmp_ok($color->as_css_hex, 'eq', '#ff667f', 'hex string with prepend');
 cmp_ok($color->as_percent_string, 'eq', '100%, 40%, 50%, 0.00', 'percent string');
 {
     my $color_z = Graphics::Color::RGB->new(
```

**Comment by gphat** [comment]
Ugh, fixed up folks. Sorry for the confusion!
